### ISSUE TITLE
imapDisconnected always connection getting disconnected.

### ISSUE THREAD

**Issue by Rajafkvp** [chirag04/mail-listener2#69]
after uploading to the firebase , i am getting below error in firebase console

Error: getaddrinfo ENOTFOUND imap.gmail.com imap.gmail.com:993
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'imap.gmail.com',
  host: 'imap.gmail.com',
  port: 993,
  source: 'socket'

**Comment by KabataMacharia** [comment]
+1

**Comment by kaeyonbaker** [comment]
I run into the same error and found my host is set to ' imap.gmail.com' with extra space.
maybe you can check the host again
